[project]
name = 'stacks-arcade'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.coin-flip-v2]
path = 'contracts/coin-flip-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.emoji-battle-v2]
path = 'contracts/emoji-battle-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.guess-the-number-v2]
path = 'contracts/guess-the-number-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.higher-lower-v2]
path = 'contracts/higher-lower-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.hot-potato-v2]
path = 'contracts/hot-potato-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.lottery-demo-v2]
path = 'contracts/lottery-demo-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.rock-paper-scissors-v2]
path = 'contracts/rock-paper-scissors-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.tournament-v2]
path = 'contracts/tournament-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.cosmetics-v2]
path = 'contracts/cosmetics-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.sip009-nft-trait-v2]
path = 'contracts/sip009-nft-trait-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.scoreboard-v2]
path = 'contracts/scoreboard-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.tic-tac-toe-v2]
path = 'contracts/tic-tac-toe-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.todo-list-v2]
path = 'contracts/todo-list-v2.clar'
clarity_version = 3
epoch = '3.0'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
