[project]
name = 'stacks-arcade'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.coin-flip-v5]
path = 'contracts/coin-flip-v5.clar'
clarity_version = 3
epoch = '3.0'

[contracts.emoji-battle-v5]
path = 'contracts/emoji-battle-v5.clar'
clarity_version = 3
epoch = '3.0'

[contracts.guess-the-number-v5]
path = 'contracts/guess-the-number-v5.clar'
clarity_version = 3
epoch = '3.0'

[contracts.higher-lower-v5]
path = 'contracts/higher-lower-v5.clar'
clarity_version = 3
epoch = '3.0'

[contracts.hot-potato-v5]
path = 'contracts/hot-potato-v5.clar'
clarity_version = 3
epoch = '3.0'

[contracts.lottery-demo-v5]
path = 'contracts/lottery-demo-v5.clar'
clarity_version = 3
epoch = '3.0'

[contracts.rock-paper-scissors-v5]
path = 'contracts/rock-paper-scissors-v5.clar'
clarity_version = 3
epoch = '3.0'

[contracts.tournament-v5]
path = 'contracts/tournament-v5.clar'
clarity_version = 3
epoch = '3.0'

[contracts.cosmetics-v5]
path = 'contracts/cosmetics-v5.clar'
clarity_version = 3
epoch = '3.0'

[contracts.sip009-nft-trait-v5]
path = 'contracts/sip009-nft-trait-v5.clar'
clarity_version = 3
epoch = '3.0'

[contracts.scoreboard-v5]
path = 'contracts/scoreboard-v5.clar'
clarity_version = 3
epoch = '3.0'

[contracts.tic-tac-toe-v5]
path = 'contracts/tic-tac-toe-v5.clar'
clarity_version = 3
epoch = '3.0'

[contracts.todo-list-v5]
path = 'contracts/todo-list-v5.clar'
clarity_version = 3
epoch = '3.0'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'

